apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: wluh1
    repository: k8s-ci-cd-jx
  - key: staging
  - key: production
  ingress:
    domain: 35.241.195.23
    kind: ingress
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: wluh1
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
